# Generated by Django 5.2.17 on 2026-10-05 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='cryptocurrency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='alerts.cryptocurrency'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_active', 'cryptocurrency'], name='alert_active_crypto_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(condition=models.Q(('target_price__gt', 0)), name='alert_target_price_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'cryptocurrency', 'alert_type', 'target_price'), name='unique_active_alert'),
        ),
    ]
