# Generated by Django 5.2.17 on 2026-10-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=5)),
                ('target_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('coingecko_id', models.CharField(max_length=100, unique=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('last_price_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'cryptocurrencies',
                'ordering': ['symbol'],
            },
        ),
    ]
