# Generated by Django 5.2.18 on 2026-10-09 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('coingecko_id', models.CharField(max_length=100, unique=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('last_price_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'cryptocurrencies',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=5)),
                ('target_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='alerts.cryptocurrency')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'cryptocurrency'], name='alert_active_crypto_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_price__gt', 0)), name='alert_target_price_gt_0'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'cryptocurrency', 'alert_type', 'target_price'), name='unique_active_alert')],
            },
        ),
    ]
